future: true
permalink: /:title/
url: http://duyanghao.github.io
name: 阿杜
author: duyanghao
qq: 
email: 1294057873@qq.com
duoshuo: duyanghao
beian: 
cnzz: 
weibo: http://weibo.com/6049751054/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
github: duyanghao
paginate: 20
highlighter: rouge
truncate: true
about: "阿杜(duyanghao)"
