future: true
permalink: /:title/
url: http://duyanghao.github.io
name: 阿杜
author: duyanghao
qq: 
email: 1294057873@qq.com
duoshuo: duyanghao
beian: 
cnzz: 
weibo: duyanghao
github: duyanghao
paginate: 20
highlighter: rouge
truncate: true
about: "阿杜(duyanghao)"
